### PR TITLE
Upgrade to prompt_toolkit 0.59.

### PR DESCRIPTION
**Pull request by jonathanslenders**
Changelog: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/CHANGELOG

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi Jonathan,

Thanks for the continued support and easy-to-understand changelogs.  I hope to free up soon to review it.

-Donne

**Comment by jonathanslenders** [comment]
Hi Donne,

Maybe wait about a week. A few small bugs in prompt-toolkit and one bigger (pasting of a block in Vi mode does not refresh the screen) have been discovered. I'm planning to push a new release very soon, and I'll update this pull request.

**Comment by donnemartin** [comment]
Thanks for the heads up!

**Comment by jonathanslenders** [comment]
Hi Donne,
I updated te commit in this pull request so that it upgrades directly to 0.60. This contains all fixes for the few bugs that have been discovered very recently.

**Comment by donnemartin** [comment]
Thanks for the update Jonathan.  Hoping to review and merge this soon.

**Comment by donnemartin** [comment]
Jonathan, I'm noticing the scroll bars don't seem to take the desired color after this change.  Here are before (left) and after (right) screenshots:

Imgur

These lines should set the scroll bar colors:

```
    Token.Menu.Completions.ProgressButton: 'bg:#003333',
    Token.Menu.Completions.ProgressBar: 'bg:#00aaaa',
```

In `style.py`:

```
return style_from_pygments(style_cls=style, style_dict={
    Token.Menu.Completions.Completion.Current: 'bg:#00aaaa #000000',
    Token.Menu.Completions.Completion: 'bg:#008888 #ffffff',
    Token.Menu.Completions.ProgressButton: 'bg:#003333',
    Token.Menu.Completions.ProgressBar: 'bg:#00aaaa',
    Token.Toolbar: 'bg:#222222 #cccccc',
    Token.Toolbar.Off: 'bg:#222222 #696969',
    Token.Toolbar.On: 'bg:#222222 #ffffff',
    Token.Toolbar.Search: 'noinherit bold',
    Token.Toolbar.Search.Text: 'nobold',
    Token.Toolbar.System: 'noinherit bold',
    Token.Toolbar.Arg: 'noinherit bold',
    Token.Toolbar.Arg.Text: 'nobold'
})
```

**Comment by jonathanslenders** [comment]
Hi Donne,

I updated the pull request to fix the issue with the colors. The change was that the scrollbars had become a reusable UI component that can be put alongside any "widget". Because of that, the naming in the style changed slightly. 

Jonathan

**Comment by donnemartin** [comment]
Great, thanks Jonathan!  I'll try to check it out this week.

**Comment by jonathanslenders** [comment]
We can close this. I made a new pull request with the changes for 1.0.0
https://github.com/donnemartin/saws/pull/83

**Comment by donnemartin** [comment]
1.0.0 merged https://github.com/donnemartin/saws/pull/83

**Pull request closed without merging**
