### PR TITLE
Add Dockerfile for running SAWS in container

### PR DESCRIPTION
**Pull request by frosforever**
Assuming Docker is installed, the container can be built by running `docker build -t saws .` and run via 
```
docker run -it -e AWS_ACCESS_KEY_ID=<key> -e AWS_SECRET_ACCESS_KEY=<secret> -e AWS_DEFAULT_REGION=<region> saws
```

The container is currently pretty large as it's based on `ubuntu:latest`. Ultimately, it would be nice if this can be based on `alpine:latest` similar to https://github.com/anigeo/docker-awscli but I'm not yet sure how to get tty to work.

Similar to `docker-awscli`, keys can be passed in via env vars as shown above or by attaching the host's `.aws` to the container `docker run -it -v ~/.aws/:/root/.aws:ro saws`

If there's interest I can attempt to shrink the image, add to the README and publish to Dockerhub.

### CODE REVIEW

**Comment by donnemartin** [comment]
@frosforever thanks for the pull request, I'll try to look at this in more detail in a day or so.

**Comment by donnemartin** [comment]
@frosforever I think this could be helpful.  We've had a few issues logged about users having difficulty installing with `pip` in their global environment due to potential permissions/dependencies.  I've been suggesting to use a [`virtualenv`](https://github.com/donnemartin/saws#virtual-environment-installation) instead.  

A container approach to running `SAWS` could be a nice addition.

**Comment by frosforever** [comment]
@donnemartin Brilliant. I'll try and make time this week to slim down the image but at least there's something here that works.
I'm also not familiar how one submits official docker repos to docker hub. I'll try and look at that as well unless someone chimes in here.

Great tool by the way!

**Comment by donnemartin** [comment]
@frosforever great, I'll merge this.  Feel free to open up another PR for the additional changes you suggested too.  Thanks!

**Comment by donnemartin** [comment]
@frosforever also, an addition to the README would be nice :)

**Pull request merged**
