### PR TITLE
Fix installation of groff and follow Dockerfile best practices

### PR DESCRIPTION
**Pull request by stilvoid**
The current Dockerfile does not install groff and doesn't follow [Dockerfile best practice](http://docs.docker.com/engine/articles/dockerfile_best-practices/).

This builds a fully working container. I've set up an automated build at <https://hub.docker.com/r/stilvoid/saws/>.

### CODE REVIEW

**Comment by cliveza** [comment]
I submitted a follow up pull request to fix my error, but @stilvoid dockerfile is better, removing mine.

**Comment by stilvoid** [comment]
Thanks @cliveza. I looked for issues or pull requests related to this problem but couldn't find any.

**Comment by donnemartin** [comment]
Thanks @stilvoid @cliveza!

**Comment by stilvoid** [comment]
Strangely, I don't see these changes in the master branch any more. Has there been a force push since?

**Comment by donnemartin** [comment]
@stilvoid  @cliveza  DOH!  I was noodling around the `develop` branch and wanted to blow away just those changes.  Looks like I accidentally toppled your changes in `master`, sorry!

I've hand merged the pull requests (it was a little messy) but we should be all set now.

To prevent similar issues in the future I set up branch protection.  Actually, I went ahead and set up branch protection for all my other repos too.

Apologies for the inconvenience, and thanks for catching it.

**Comment by stilvoid** [comment]
No worries. I'd have happily rebased and resubmitted my PR but this works just fine :)

I'll update my fork so the automated build [here](https://hub.docker.com/r/stilvoid/saws/) is up to date.

**Pull request merged**
